require-license: false
require-known-license: false

allow:
  - Apache*
  - MIT*
  - BSD*
  - ISC
  - MPL*
  - OpenSSL
  - GooglePatentsFile
  - Unlicense
  - CC0*
  - GPL-3.0*
  - 0BSD
  - HPND
  - ZPL*
  - Dual License
  - UNKNOWN
  - PSF*
  - MIT/X11

ignore-packages:
  - "github.com/timo-reymann/*"
