excludes:
  paths:
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Only used for documentation, not provided as source"
  - pattern: "requirements-docs.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Only used for documentation, not provided as source"
  - pattern: "python_wrapper/pydoctor-theme/**"
    reason: "DOCUMENTATION_OF"
    comment: "Only used for python package reference docs"

curations:
  license_findings:
    - path: "CONTRIBUTING.md"
      start_lines: "48"
      detected_license: "NOASSERTION"
      reason: "INCORRECT"
      comment: "False positive - the text clearly states GPL-3.0 license."
      concluded_license: "GPL-3.0-only"
    - path: "internal/netrc/*"
      detected_license: "BSD-3-Clause"
      reason: "INCORRECT"
      comment: "Part of project and compatible with the root license"
      concluded_license: "GPL-3.0-only"      
