test:
  stage: test
  extends: .mod_download
  coverage: '/^coverage: (\d+.\d+)% of statements$/'
  script:
    - gotestsum --junitfile junit.xml --format testname -- -race -coverprofile=coverage.txt -covermode=atomic ./...
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    when: always
    paths:
      - junit.xml
      - coverage.txt
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
      when: never
