publish-chart:
  extends: .helm-package
  stage: release
  variables:
    HELM_CHART_DIR: chart
    HELM_CHART_VERSION: ${CI_COMMIT_TAG}
    HELM_APP_VERSION: ${CI_COMMIT_TAG}
    HELM_PUSH: true
    HELM_REGISTRY_PROJECT: platform-charts
