nav:
  - index.md
  - installation.md
  - usage
  - extending
  - Development:
      - add-builtin-check.md
      - development/*.md
      - Architecture Decision Records:
          - adr/*.md
  - how-it-works
  - Check Reference:
      - checks/*.md

ignore:
  - adr/000-TEMPLATE.md
